swagger: "2.0"
info:
  title: Demo pro Rohlik
  description: Ukol pro rohlik
  version: 0.0.1
servers:
  - url: http://localhost
paths:
  /order:
    post:
      summary: Create new order
      description: Vytvori novou objednavku
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      properties:
        id:
          type: integer
        name:
          type: string
      # Both properties are required
      required:
        - id
        - name